In [1]:
# Reference: https://youtu.be/rzilPq7xXC4
import tensorflow as tf
import numpy as np
import math

sess = tf.InteractiveSession()

In [2]:
x1 = tf.Variable(tf.truncated_normal([5],
                                    mean=3, stddev=1./math.sqrt(5)))
x2 = tf.Variable(tf.truncated_normal([5],
                                    mean=-1, stddev=1./math.sqrt(5)))
x3 = tf.Variable(tf.truncated_normal([5],
                                    mean=0, stddev=1./math.sqrt(5)))

In [3]:
sess.run(tf.global_variables_initializer())

In [6]:
sqx2 = x2 * x2
print(x2.eval())
print(sqx2.eval())

[-0.43010956 -1.13535237 -0.99287236 -1.34988117 -0.69460398]
[ 0.18499424  1.28902507  0.9857955   1.8221792   0.48247468]


In [7]:
logx1 = tf.log(x1)
print(x1.eval())
print(logx1.eval())

[ 3.05549836  2.80742431  2.46314025  2.74482155  3.07706165]
[ 1.11694264  1.03226745  0.90143704  1.00971603  1.12397516]


In [8]:
sigx3 = tf.sigmoid(x3)
print(x3.eval())
print(sigx3.eval())

[-0.0919938  -0.19651921 -0.11295315 -0.49654815  0.16319777]
[ 0.47701776  0.45102769  0.47179174  0.3783522   0.54070914]


In [11]:
w1 = tf.constant(0.1)
w2 = tf.constant(0.2)
sess.run(tf.global_variables_initializer())
n1 = tf.sigmoid(w1*x1 + w2*x2)
print((w1*x1).eval())
print((w2*x2).eval())
print(n1.eval())

[ 0.33172268  0.31661573  0.27933365  0.3247796   0.26437524]
[-0.16178624 -0.22296892 -0.23852877 -0.21238981 -0.30128402]
[ 0.54238218  0.52339464  0.51019979  0.52806789  0.49077386]
