In [1]:
# Reference: https://youtu.be/zgV-WzLyrYE
import tensorflow as tf

In [ ]:
# Tensor

In [8]:
a = tf.constant([2,5])
b = tf.constant([3,7])

In [9]:
c = tf.add(a,b)

In [10]:
session = tf.Session()

In [12]:
with tf.Session() as sess:
    result = session.run(c)
    print (result)

[ 5 12]


In [16]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant([[[1,2,3],[2,3,4],[3,4,5]], [[4,5,6],[5,6,7],[6,7,8]], [[7,8,9],[8,9,10],[9,10,11]]])
with tf.Session() as sess:
    result = sess.run(Scalar)
    print "Scalar (1 entry):\n %s \n" % result
    result = sess.run(Vector)
    print "Vector (3 entries):\n %s \n" % result
    result = sess.run(Matrix)
    print "Matrix (3x3 entries):\n %s \n" % result
    result = sess.run(Tensor)
    print "Tensor (3x3x3 entries) :\n %s \n" % result

Scalar (1 entry):
 [2] 

Vector (3 entries):
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [19]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as sess:
    result = sess.run(Matrix_one)
    print "Matrix_one: \n %s \n" % result
    result = sess.run(Matrix_two)
    print "Matrix_two: \n %s \n" % result
    result = sess.run(first_operation)
    print "Defined using tensorflow function:"
    print(result)

Matrix_one: 
 [[2 3]
 [3 4]] 

Matrix_two: 
 [[2 3]
 [3 4]] 

Defined using tensorflow function:
[[13 18]
 [18 25]]


In [ ]:
# Variable

In [20]:
state = tf.Variable(0)

In [21]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [23]:
# init_op = tf.initialize_all_variables() # deprecated
init_op = tf.global_variables_initializer()

In [24]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [25]:
 # Placeholder

In [26]:
a = tf.placeholder(tf.float32)
b = a*2

In [27]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print result

7.0


In [28]:
dictionary = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print result

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]
