In [125]:
import numpy as np
import random
import copy
#import matplotlib.pyplot as plt

train_data = np.genfromtxt('../data/assign2_train_data.txt', delimiter=',')
#print "train_data:", train_data

t = train_data[:,2]
hu = train_data[:,3]
lt = train_data[:,4]
co2 = train_data[:,5]
hu_r = train_data[:,6]

o = train_data[:,7]

#data
data = np.column_stack((t, hu, lt, co2, hu_r))
print "data:", data

print "np.shape(train_data): ", np.shape(train_data)
#print "np.shape(t): ", np.shape(t)

print "t: ", t
print "hu: ", hu
print "lt: ", lt
print "co2: ", co2
print "hu_r: ", hu_r
print "o: ", o

data: [[  2.31800000e+01   2.72720000e+01   4.26000000e+02   7.21250000e+02
    4.79298818e-03]
 [  2.31500000e+01   2.72675000e+01   4.29500000e+02   7.14000000e+02
    4.78344095e-03]
 [  2.31500000e+01   2.72450000e+01   4.26000000e+02   7.13500000e+02
    4.77946352e-03]
 ..., 
 [  2.11000000e+01   3.60950000e+01   4.33000000e+02   7.98500000e+02
    5.59563902e-03]
 [  2.11000000e+01   3.62600000e+01   4.33000000e+02   8.20333333e+02
    5.62144937e-03]
 [  2.11000000e+01   3.62000000e+01   4.47000000e+02   8.21000000e+02
    5.61206354e-03]]
np.shape(train_data):  (8143, 8)
t:  [ 23.18  23.15  23.15 ...,  21.1   21.1   21.1 ]
hu:  [ 27.272   27.2675  27.245  ...,  36.095   36.26    36.2   ]
lt:  [ 426.   429.5  426.  ...,  433.   433.   447. ]
co2:  [ 721.25        714.          713.5        ...,  798.5         820.33333333
  821.        ]
hu_r:  [ 0.00479299  0.00478344  0.00477946 ...,  0.00559564  0.00562145
  0.00561206]
o:  [ 1.  1.  1. ...,  1.  1.  1.]


In [39]:
def normalize(data):
    #normalize train data
    #normalize t
    t = data[:, 0]
    t_min = np.min(t)
    t_max = np.max(t)
    d_t = t_max - t_min
    #normalized t: n_t
    n_t = []
    for each in t:
        n_t.append((each - t_min) / d_t)

    #normalize hu
    hu = data[:, 1]
    hu_min = np.min(hu)
    hu_max = np.max(hu)
    d_hu = hu_max - hu_min
    #normalized h: n_hu
    n_hu = []
    for each in hu:
        n_hu.append((each - hu_min) / d_hu)

    #normalize lt
    lt = data[:, 2]
    lt_min = np.min(lt)
    lt_max = np.max(lt)
    d_lt = lt_max - lt_min
    #normalized lt: n_lt
    n_lt = []
    for each in lt:
        n_lt.append((each - lt_min) / d_lt)

    #normalize co2
    co2 = data[:, 3]
    co2_min = np.min(co2)
    co2_max = np.max(co2)
    d_co2 = co2_max - co2_min
    #normalized co2: n_co2
    n_co2 = []
    for each in co2:
        n_co2.append((each - co2_min) / d_co2)

    #normalize hu_r
    hu_r = data[:, 4]
    hu_r_min = np.min(hu_r)
    hu_r_max = np.max(hu_r)
    d_hu_r = hu_r_max - hu_r_min
    #normalized hu_r: n_hu_r
    n_hu_r = []
    for each in hu_r:
        n_hu_r.append((each - hu_r_min) / d_hu_r)

    #normalized data: n_data
    n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r))
    
    return n_data

In [40]:
n_data = normalize(data)
print "n_data:", n_data

n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762]]


In [41]:
def initialize_weights1():
    w_t = random.random()
    w_hu = random.random()
    w_lt = random.random()
    w_co2 = random.random()
    w_hu_r = random.random()
    b = random.random()

    #weights
    ws1 = [w_t, w_hu, w_lt, w_co2, w_hu_r, b]
    return ws1

init_ws1 = initialize_weights1()
ws1 = copy.deepcopy(init_ws1)
print "ws1: ", ws1

ws1:  [0.15458866936394067, 0.37590508614686047, 0.15657332505492216, 0.20041655545272552, 0.7255452972090953, 0.22384957625198354]


In [63]:
# initialize random weights from layer with i neurons to layer with j neurons -- fully connected layer including bias
# note that each row is the weights list from former layer to jth neuron in the latter layer
def initialize_weights(i, j):
    ws = np.random.rand(j, i + 1)
    return ws

In [64]:
# test inner 
a = [1, 2, 3]
b = [2, 0, 5]
np.inner(a, b)

17

In [134]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def activation(x): # use sigmoid as activation function
    a = sigmoid(x)
    if a >= 0.5:
        return 1
    else:
        return 0

def perceptron(ins, ws):
    sum = 0
    for x, w in zip(ins, ws):
        sum += x * w
    return activation(sum)

# Reference: http://cs229.stanford.edu/notes/cs229-notes1.pdf
# mean squared error
def error_function(o, y):
    return (o - y) ** 2 / (2 * len(o))

# lr - learning rate
# bs - batch size
# set lr and bs
lr = 0.001
bs = 1

def train(n_data, o, lr, H, bs):
    print "Training starts: len of data:", len(n_data)
    
    accuracies = []
    epoch = 0
    n_t = n_data[:, 0]
    n_hu = n_data[:, 1]
    n_lt = n_data[:, 2]
    n_co2 = n_data[:, 3]
    n_hu_r = n_data[:, 4]
    n_b = np.ones(len(n_t))
    
    train_n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r, n_b))
    print "n_t:", n_t
    print "n_hu:", n_hu
    print "n_lt:", n_lt
    print "n_b:", n_b
    print "train_n_data:", train_n_data
    
    #ws0 are the weights from input layer to hidden layer
    init_ws0 = initialize_weights(5, H)
    ws0 = copy.deepcopy(init_ws0)
    print "ws0 before training:", ws0

    #ws1
    init_ws1 = initialize_weights(H, 1)
    ws1 = copy.deepcopy(init_ws1)
    print "ws1 before training", ws1
    
    epoch = 1
    while epoch <= 10000:
        
        i_data = 0 # index in the traning data list
        i_bs = 0 # index of batch size
        err2 = 0 # output layer error
        # one epoch
        while i_data < len(n_t):
            
            # each hidden neuron
            hidden_os = [] # hidden layer outputs
            for i in range(H):
                #print "i_data:",i_data
                hidden_o_i = activation(np.inner(ws0[i], train_n_data[i_data])) # one output of one hidden layer neuron
                hidden_os.append(hidden_o_i)

            hidden_os.append(1) # append bias
            #print "hidden_os:", hidden_os
            
            net_o = np.inner(hidden_os, ws1) # output layer output
            #print "net_o:", net_o
            
            err2 += error_function(net_o, o[i_data]) # output layer error
            # only update weights after bs batch_size
            #print "o:",o
            if i_bs >= bs:
                
                err2 = 0
                i_bs = -1
                
            hidden_os = []
            i_data += 1
            i_bs += 1
        
        
        epoch += 1
    
    
    '''
    while epoch <= 10000:
        # train
        i = 0
        for (n_t_i, n_hu_i, n_lt_i, n_co2_i, n_hu_r_i, o_i) in zip(n_t, n_hu, n_lt, n_co2, n_hu_r, o):
            sum_error_w_t = 0
            sum_error_w_hu = 0
            sum_error_w_lt = 0
            sum_error_w_co2 = 0
            sum_error_w_hu_r = 0
            sum_error_b = 0
            
            error = o_i - (n_t_i * ws[0] + n_hu_i * ws[1] + n_lt_i * ws[2] + n_co2_i * ws[3] + n_hu_r_i * ws[4] + ws[5])
            sum_error_w_t += error * n_t_i
            sum_error_w_hu += error * n_hu_i
            sum_error_w_lt += error * n_lt_i
            sum_error_w_co2 += error * n_co2_i
            sum_error_w_hu_r += error * n_hu_r_i
            sum_error_b += error
            
            if i >= bs: # only update weights after one batch size
                ws[0] += lr * sum_error_w_t
                ws[1] += lr * sum_error_w_hu
                ws[2] += lr * sum_error_w_lt
                ws[3] += lr * sum_error_w_co2
                ws[4] += lr * sum_error_w_hu_r
                ws[5] += lr * sum_error_b
                sum_error_w_t = 0
                sum_error_w_hu = 0
                sum_error_w_lt = 0
                sum_error_w_co2 = 0
                sum_error_w_hu_r = 0
                sum_error_b = 0
                i = 1
                continue
            
            #test every epoch
            accuracy = get_one_feedforward_accuracy(n_data, ws0, ws1, o)
            accuracies.append(accuracy)
            #if epoch % 100 == 0:
            print "epoch:", epoch, " accuracy:",accuracy
            
            i += 1
        
        # count 
        epoch += 1
    '''
    print "Training ends."
    print "Initial input to hidden layer weights:", init_ws0
    print "Trained input to hidden layer weights:", ws0
    print "Initial hidden to output layer weights:", init_ws1
    print "Trained hidden to output layer weights:", ws1
    plot_accuracy(accuracies, lr, bs, stage="train")
    
def test(test_data, o, lr, bs):
    #normalize test data
    #normalize t
    n_test_data = normalize(test_data)
    n_t = n_test_data[:, 0]
    n_hu = n_test_data[:, 1]
    n_lt = n_test_data[:, 2]
    n_co2 = n_test_data[:, 3]
    n_hu_r = n_test_data[:, 4]
    for (n_t_i, n_hu_i, n_lt_i, n_co2_i, n_hu_r_i, o_i) in zip(n_t, n_hu, n_lt, n_co2, n_hu_r, o):
        #test every epoch
        accuracy = get_one_feedforward_accuracy(n_data, ws, o)
        accuracies.append(accuracy)
        print "epoch:", epoch, " accuracy:",accuracy
    plot_accuracy(accuracies, lr, bs, stage="test")
        
def get_one_feedforward_accuracy(n_data, ws0, ws1, o):
    
    #calculate accuracy
    #outputs
    os = []
    for each in zip(n_data):
        for ins in each:
            print "ins: ", ins
            #perceptron(ins, ws)
            
    #count correct output number
    correct_cnt = 0
    for o_i, os_i in zip(o, os):
        if (o_i == os_i):
            correct_cnt += 1
    accuracy = float(correct_cnt) / float(len(o))
    ##calculate accuracy
    return accuracy
    
def plot_accuracy(accuracies, lr, bs, stage):
    accs_y = np.array(accuracies)
    epochs = []
    for i in range(len(accuracies)):
        epochs.append(i)
    epochs_x = np.array(epochs)
    plt.plot(epochs_x, accs_y, epochs_x)
    title = stage
    title += ' lr:'
    title += str(lr)
    title += ' batch_size:'
    title += str(bs)
    plt.title(title)
    plt.xlabel('epoch')
    plt.ylabel('accuracy')
    plt.show()

In [135]:
train(n_data, o, lr = 0.0001, H = 1, bs = 1)

Training starts: len of data: 8143
n_t: [ 1.          0.99282297  0.99282297 ...,  0.50239234  0.50239234
  0.50239234]
n_hu: [ 0.47053302  0.47033188  0.46932618 ...,  0.86490111  0.87227623
  0.86959437]
n_lt: [ 0.27549041  0.27775383  0.27549041 ...,  0.28001725  0.28001725
  0.28907092]
n_b: [ 1.  1.  1. ...,  1.  1.  1.]
train_n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842  1.        ]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723  1.        ]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106  1.        ]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752  1.        ]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635  1.        ]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762  1.        ]]
ws0 before training: [[ 0.43676739  0.19730835  0.27864346  0.39972774  0.16554043  0.94882063]]
ws1 before training [[ 0.01931784  0.46565504]]
i_data: 0
i_data: 1
i_data: 2
i_data: 3
i_data: 4
i_dat

i_data: 1270
i_data: 1271
i_data: 1272
i_data: 1273
i_data: 1274
i_data: 1275
i_data: 1276
i_data: 1277
i_data: 1278
i_data: 1279
i_data: 1280
i_data: 1281
i_data: 1282
i_data: 1283
i_data: 1284
i_data: 1285
i_data: 1286
i_data: 1287
i_data: 1288
i_data: 1289
i_data: 1290
i_data: 1291
i_data: 1292
i_data: 1293
i_data: 1294
i_data: 1295
i_data: 1296
i_data: 1297
i_data: 1298
i_data: 1299
i_data: 1300
i_data: 1301
i_data: 1302
i_data: 1303
i_data: 1304
i_data: 1305
i_data: 1306
i_data: 1307
i_data: 1308
i_data: 1309
i_data: 1310
i_data: 1311
i_data: 1312
i_data: 1313
i_data: 1314
i_data: 1315
i_data: 1316
i_data: 1317
i_data: 1318
i_data: 1319
i_data: 1320
i_data: 1321
i_data: 1322
i_data: 1323
i_data: 1324
i_data: 1325
i_data: 1326
i_data: 1327
i_data: 1328
i_data: 1329
i_data: 1330
i_data: 1331
i_data: 1332
i_data: 1333
i_data: 1334
i_data: 1335
i_data: 1336
i_data: 1337
i_data: 1338
i_data: 1339
i_data: 1340
i_data: 1341
i_data: 1342
i_data: 1343
i_data: 1344
i_data: 1345
i_data: 1346

i_data: 2002
i_data: 2003
i_data: 2004
i_data: 2005
i_data: 2006
i_data: 2007
i_data: 2008
i_data: 2009
i_data: 2010
i_data: 2011
i_data: 2012
i_data: 2013
i_data: 2014
i_data: 2015
i_data: 2016
i_data: 2017
i_data: 2018
i_data: 2019
i_data: 2020
i_data: 2021
i_data: 2022
i_data: 2023
i_data: 2024
i_data: 2025
i_data: 2026
i_data: 2027
i_data: 2028
i_data: 2029
i_data: 2030
i_data: 2031
i_data: 2032
i_data: 2033
i_data: 2034
i_data: 2035
i_data: 2036
i_data: 2037
i_data: 2038
i_data: 2039
i_data: 2040
i_data: 2041
i_data: 2042
i_data: 2043
i_data: 2044
i_data: 2045
i_data: 2046
i_data: 2047
i_data: 2048
i_data: 2049
i_data: 2050
i_data: 2051
i_data: 2052
i_data: 2053
i_data: 2054
i_data: 2055
i_data: 2056
i_data: 2057
i_data: 2058
i_data: 2059
i_data: 2060
i_data: 2061
i_data: 2062
i_data: 2063
i_data: 2064
i_data: 2065
i_data: 2066
i_data: 2067
i_data: 2068
i_data: 2069
i_data: 2070
i_data: 2071
i_data: 2072
i_data: 2073
i_data: 2074
i_data: 2075
i_data: 2076
i_data: 2077
i_data: 2078

i_data: 2715
i_data: 2716
i_data: 2717
i_data: 2718
i_data: 2719
i_data: 2720
i_data: 2721
i_data: 2722
i_data: 2723
i_data: 2724
i_data: 2725
i_data: 2726
i_data: 2727
i_data: 2728
i_data: 2729
i_data: 2730
i_data: 2731
i_data: 2732
i_data: 2733
i_data: 2734
i_data: 2735
i_data: 2736
i_data: 2737
i_data: 2738
i_data: 2739
i_data: 2740
i_data: 2741
i_data: 2742
i_data: 2743
i_data: 2744
i_data: 2745
i_data: 2746
i_data: 2747
i_data: 2748
i_data: 2749
i_data: 2750
i_data: 2751
i_data: 2752
i_data: 2753
i_data: 2754
i_data: 2755
i_data: 2756
i_data: 2757
i_data: 2758
i_data: 2759
i_data: 2760
i_data: 2761
i_data: 2762
i_data: 2763
i_data: 2764
i_data: 2765
i_data: 2766
i_data: 2767
i_data: 2768
i_data: 2769
i_data: 2770
i_data: 2771
i_data: 2772
i_data: 2773
i_data: 2774
i_data: 2775
i_data: 2776
i_data: 2777
i_data: 2778
i_data: 2779
i_data: 2780
i_data: 2781
i_data: 2782
i_data: 2783
i_data: 2784
i_data: 2785
i_data: 2786
i_data: 2787
i_data: 2788
i_data: 2789
i_data: 2790
i_data: 2791

i_data: 3540
i_data: 3541
i_data: 3542
i_data: 3543
i_data: 3544
i_data: 3545
i_data: 3546
i_data: 3547
i_data: 3548
i_data: 3549
i_data: 3550
i_data: 3551
i_data: 3552
i_data: 3553
i_data: 3554
i_data: 3555
i_data: 3556
i_data: 3557
i_data: 3558
i_data: 3559
i_data: 3560
i_data: 3561
i_data: 3562
i_data: 3563
i_data: 3564
i_data: 3565
i_data: 3566
i_data: 3567
i_data: 3568
i_data: 3569
i_data: 3570
i_data: 3571
i_data: 3572
i_data: 3573
i_data: 3574
i_data: 3575
i_data: 3576
i_data: 3577
i_data: 3578
i_data: 3579
i_data: 3580
i_data: 3581
i_data: 3582
i_data: 3583
i_data: 3584
i_data: 3585
i_data: 3586
i_data: 3587
i_data: 3588
i_data: 3589
i_data: 3590
i_data: 3591
i_data: 3592
i_data: 3593
i_data: 3594
i_data: 3595
i_data: 3596
i_data: 3597
i_data: 3598
i_data: 3599
i_data: 3600
i_data: 3601
i_data: 3602
i_data: 3603
i_data: 3604
i_data: 3605
i_data: 3606
i_data: 3607
i_data: 3608
i_data: 3609
i_data: 3610
i_data: 3611
i_data: 3612
i_data: 3613
i_data: 3614
i_data: 3615
i_data: 3616

KeyboardInterrupt: 

In [133]:
train(n_data, o, lr = 0.0001, H = 5, bs = 1)

Training starts: len of data: 8143
n_t: [ 1.          0.99282297  0.99282297 ...,  0.50239234  0.50239234
  0.50239234]
n_hu: [ 0.47053302  0.47033188  0.46932618 ...,  0.86490111  0.87227623
  0.86959437]
n_lt: [ 0.27549041  0.27775383  0.27549041 ...,  0.28001725  0.28001725
  0.28907092]
n_b: [ 1.  1.  1. ...,  1.  1.  1.]
train_n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842  1.        ]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723  1.        ]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106  1.        ]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752  1.        ]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635  1.        ]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762  1.        ]]
ws0 before training: [[ 0.19629865  0.67558866  0.34915578  0.90783372  0.32780405  0.99011172]
 [ 0.94945527  0.33561477  0.48324025  0.56502282  0.90832387  0.52237901]
 [ 0.7201301   0.10087328  0.

i_data: 226
i_data: 226
i_data: 226
i_data: 227
i_data: 227
i_data: 227
i_data: 227
i_data: 227
err2: [ 4.0491886]
i_data: 228
i_data: 228
i_data: 228
i_data: 228
i_data: 228
i_data: 229
i_data: 229
i_data: 229
i_data: 229
i_data: 229
err2: [ 4.0491886]
i_data: 230
i_data: 230
i_data: 230
i_data: 230
i_data: 230
i_data: 231
i_data: 231
i_data: 231
i_data: 231
i_data: 231
err2: [ 4.0491886]
i_data: 232
i_data: 232
i_data: 232
i_data: 232
i_data: 232
i_data: 233
i_data: 233
i_data: 233
i_data: 233
i_data: 233
err2: [ 4.0491886]
i_data: 234
i_data: 234
i_data: 234
i_data: 234
i_data: 234
i_data: 235
i_data: 235
i_data: 235
i_data: 235
i_data: 235
err2: [ 4.0491886]
i_data: 236
i_data: 236
i_data: 236
i_data: 236
i_data: 236
i_data: 237
i_data: 237
i_data: 237
i_data: 237
i_data: 237
err2: [ 4.0491886]
i_data: 238
i_data: 238
i_data: 238
i_data: 238
i_data: 238
i_data: 239
i_data: 239
i_data: 239
i_data: 239
i_data: 239
err2: [ 4.0491886]
i_data: 240
i_data: 240
i_data: 240
i_data: 240
i_d

i_data: 365
i_data: 365
i_data: 365
i_data: 365
err2: [ 4.0491886]
i_data: 366
i_data: 366
i_data: 366
i_data: 366
i_data: 366
i_data: 367
i_data: 367
i_data: 367
i_data: 367
i_data: 367
err2: [ 4.0491886]
i_data: 368
i_data: 368
i_data: 368
i_data: 368
i_data: 368
i_data: 369
i_data: 369
i_data: 369
i_data: 369
i_data: 369
err2: [ 4.0491886]
i_data: 370
i_data: 370
i_data: 370
i_data: 370
i_data: 370
i_data: 371
i_data: 371
i_data: 371
i_data: 371
i_data: 371
err2: [ 4.0491886]
i_data: 372
i_data: 372
i_data: 372
i_data: 372
i_data: 372
i_data: 373
i_data: 373
i_data: 373
i_data: 373
i_data: 373
err2: [ 4.0491886]
i_data: 374
i_data: 374
i_data: 374
i_data: 374
i_data: 374
i_data: 375
i_data: 375
i_data: 375
i_data: 375
i_data: 375
err2: [ 4.0491886]
i_data: 376
i_data: 376
i_data: 376
i_data: 376
i_data: 376
i_data: 377
i_data: 377
i_data: 377
i_data: 377
i_data: 377
err2: [ 4.0491886]
i_data: 378
i_data: 378
i_data: 378
i_data: 378
i_data: 378
i_data: 379
i_data: 379
i_data: 379
i_d

i_data: 504
i_data: 505
i_data: 505
i_data: 505
i_data: 505
i_data: 505
err2: [ 4.0491886]
i_data: 506
i_data: 506
i_data: 506
i_data: 506
i_data: 506
i_data: 507
i_data: 507
i_data: 507
i_data: 507
i_data: 507
err2: [ 4.0491886]
i_data: 508
i_data: 508
i_data: 508
i_data: 508
i_data: 508
i_data: 509
i_data: 509
i_data: 509
i_data: 509
i_data: 509
err2: [ 4.0491886]
i_data: 510
i_data: 510
i_data: 510
i_data: 510
i_data: 510
i_data: 511
i_data: 511
i_data: 511
i_data: 511
i_data: 511
err2: [ 4.0491886]
i_data: 512
i_data: 512
i_data: 512
i_data: 512
i_data: 512
i_data: 513
i_data: 513
i_data: 513
i_data: 513
i_data: 513
err2: [ 4.0491886]
i_data: 514
i_data: 514
i_data: 514
i_data: 514
i_data: 514
i_data: 515
i_data: 515
i_data: 515
i_data: 515
i_data: 515
err2: [ 4.0491886]
i_data: 516
i_data: 516
i_data: 516
i_data: 516
i_data: 516
i_data: 517
i_data: 517
i_data: 517
i_data: 517
i_data: 517
err2: [ 4.0491886]
i_data: 518
i_data: 518
i_data: 518
i_data: 518
i_data: 518
i_data: 519
i_d

i_data: 654
i_data: 655
i_data: 655
i_data: 655
i_data: 655
i_data: 655
err2: [ 4.0491886]
i_data: 656
i_data: 656
i_data: 656
i_data: 656
i_data: 656
i_data: 657
i_data: 657
i_data: 657
i_data: 657
i_data: 657
err2: [ 4.0491886]
i_data: 658
i_data: 658
i_data: 658
i_data: 658
i_data: 658
i_data: 659
i_data: 659
i_data: 659
i_data: 659
i_data: 659
err2: [ 4.0491886]
i_data: 660
i_data: 660
i_data: 660
i_data: 660
i_data: 660
i_data: 661
i_data: 661
i_data: 661
i_data: 661
i_data: 661
err2: [ 4.0491886]
i_data: 662
i_data: 662
i_data: 662
i_data: 662
i_data: 662
i_data: 663
i_data: 663
i_data: 663
i_data: 663
i_data: 663
err2: [ 4.0491886]
i_data: 664
i_data: 664
i_data: 664
i_data: 664
i_data: 664
i_data: 665
i_data: 665
i_data: 665
i_data: 665
i_data: 665
err2: [ 4.0491886]
i_data: 666
i_data: 666
i_data: 666
i_data: 666
i_data: 666
i_data: 667
i_data: 667
i_data: 667
i_data: 667
i_data: 667
err2: [ 4.0491886]
i_data: 668
i_data: 668
i_data: 668
i_data: 668
i_data: 668
i_data: 669
i_d

i_data: 809
i_data: 809
i_data: 809
i_data: 809
i_data: 809
err2: [ 4.0491886]
i_data: 810
i_data: 810
i_data: 810
i_data: 810
i_data: 810
i_data: 811
i_data: 811
i_data: 811
i_data: 811
i_data: 811
err2: [ 4.0491886]
i_data: 812
i_data: 812
i_data: 812
i_data: 812
i_data: 812
i_data: 813
i_data: 813
i_data: 813
i_data: 

KeyboardInterrupt: 

In [111]:
test_data = np.genfromtxt('../data/assign2_test_data.txt', delimiter=',')
# print "test_data:", test_data
test(test_data, o, lr, bs)

NameError: global name 'ws' is not defined