In [125]:
'''
Author: Bryan Bo Cao
Email: boca7588@colorado.edu or bo.cao-1@colorado.edu
Github Repo: https://github.com/BryanBo-Cao/neuralnets-deeplearning

Note that input layer is noted as layer0, hidden layer is noted as layer1, and output layer is noted is layer2
'''
import numpy as np
import random
import copy
#import matplotlib.pyplot as plt

train_data = np.genfromtxt('../data/assign2_train_data.txt', delimiter=',')
#print "train_data:", train_data

t = train_data[:,2]
hu = train_data[:,3]
lt = train_data[:,4]
co2 = train_data[:,5]
hu_r = train_data[:,6]

o = train_data[:,7]

#data
data = np.column_stack((t, hu, lt, co2, hu_r))
print "data:", data

print "np.shape(train_data): ", np.shape(train_data)
#print "np.shape(t): ", np.shape(t)

print "t: ", t
print "hu: ", hu
print "lt: ", lt
print "co2: ", co2
print "hu_r: ", hu_r
print "o: ", o

data: [[  2.31800000e+01   2.72720000e+01   4.26000000e+02   7.21250000e+02
    4.79298818e-03]
 [  2.31500000e+01   2.72675000e+01   4.29500000e+02   7.14000000e+02
    4.78344095e-03]
 [  2.31500000e+01   2.72450000e+01   4.26000000e+02   7.13500000e+02
    4.77946352e-03]
 ..., 
 [  2.11000000e+01   3.60950000e+01   4.33000000e+02   7.98500000e+02
    5.59563902e-03]
 [  2.11000000e+01   3.62600000e+01   4.33000000e+02   8.20333333e+02
    5.62144937e-03]
 [  2.11000000e+01   3.62000000e+01   4.47000000e+02   8.21000000e+02
    5.61206354e-03]]
np.shape(train_data):  (8143, 8)
t:  [ 23.18  23.15  23.15 ...,  21.1   21.1   21.1 ]
hu:  [ 27.272   27.2675  27.245  ...,  36.095   36.26    36.2   ]
lt:  [ 426.   429.5  426.  ...,  433.   433.   447. ]
co2:  [ 721.25        714.          713.5        ...,  798.5         820.33333333
  821.        ]
hu_r:  [ 0.00479299  0.00478344  0.00477946 ...,  0.00559564  0.00562145
  0.00561206]
o:  [ 1.  1.  1. ...,  1.  1.  1.]


In [39]:
def normalize(data):
    #normalize train data
    #normalize t
    t = data[:, 0]
    t_min = np.min(t)
    t_max = np.max(t)
    d_t = t_max - t_min
    #normalized t: n_t
    n_t = []
    for each in t:
        n_t.append((each - t_min) / d_t)

    #normalize hu
    hu = data[:, 1]
    hu_min = np.min(hu)
    hu_max = np.max(hu)
    d_hu = hu_max - hu_min
    #normalized h: n_hu
    n_hu = []
    for each in hu:
        n_hu.append((each - hu_min) / d_hu)

    #normalize lt
    lt = data[:, 2]
    lt_min = np.min(lt)
    lt_max = np.max(lt)
    d_lt = lt_max - lt_min
    #normalized lt: n_lt
    n_lt = []
    for each in lt:
        n_lt.append((each - lt_min) / d_lt)

    #normalize co2
    co2 = data[:, 3]
    co2_min = np.min(co2)
    co2_max = np.max(co2)
    d_co2 = co2_max - co2_min
    #normalized co2: n_co2
    n_co2 = []
    for each in co2:
        n_co2.append((each - co2_min) / d_co2)

    #normalize hu_r
    hu_r = data[:, 4]
    hu_r_min = np.min(hu_r)
    hu_r_max = np.max(hu_r)
    d_hu_r = hu_r_max - hu_r_min
    #normalized hu_r: n_hu_r
    n_hu_r = []
    for each in hu_r:
        n_hu_r.append((each - hu_r_min) / d_hu_r)

    #normalized data: n_data
    n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r))
    
    return n_data

In [40]:
n_data = normalize(data)
print "n_data:", n_data

n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762]]


In [41]:
def initialize_weights1():
    w_t = random.random()
    w_hu = random.random()
    w_lt = random.random()
    w_co2 = random.random()
    w_hu_r = random.random()
    b = random.random()

    #weights
    ws1 = [w_t, w_hu, w_lt, w_co2, w_hu_r, b]
    return ws1

init_ws1 = initialize_weights1()
ws1 = copy.deepcopy(init_ws1)
print "ws1: ", ws1

ws1:  [0.15458866936394067, 0.37590508614686047, 0.15657332505492216, 0.20041655545272552, 0.7255452972090953, 0.22384957625198354]


In [63]:
# initialize random weights from layer with i neurons to layer with j neurons -- fully connected layer including bias
# note that each row is the weights list from former layer to jth neuron in the latter layer
def initialize_weights(i, j):
    ws = np.random.rand(j, i + 1)
    return ws

In [156]:
# test inner 
a = [1, 2, 3]
b = [2, 0, 5]
c = 4
#np.inner(a, b)
np.inner(a, c)

array([ 4,  8, 12])

In [196]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Reference: https://www.youtube.com/watch?v=GlcnxUlrtek
def sigmoidPrime(x):
    #Derivative of Sigmoid Function
    return np.exp(-x) / ((1 + np.exp(-x) ** 2))

def activation(x): # use sigmoid as activation function
    a = sigmoid(x)
    if a >= 0.5:
        return 1
    else:
        return 0

def perceptron(ins, ws):
    sum = 0
    for x, w in zip(ins, ws):
        sum += x * w
    return activation(sum)

# Reference: http://cs229.stanford.edu/notes/cs229-notes1.pdf
# squared error
def error_function(o, y):
    return (o - y) ** 2 / 2

# lr - learning rate
# bs - batch size
# set lr and bs
lr = 0.001
bs = 1

def train(n_data, o, lr, H, bs):
    print "Training starts: len of data:", len(n_data)
    
    accuracies = []
    epoch = 0
    n_t = n_data[:, 0]
    n_hu = n_data[:, 1]
    n_lt = n_data[:, 2]
    n_co2 = n_data[:, 3]
    n_hu_r = n_data[:, 4]
    n_b = np.ones(len(n_t))
    
    train_n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r, n_b))
    print "n_t:", n_t
    print "n_hu:", n_hu
    print "n_lt:", n_lt
    print "n_b:", n_b
    print "train_n_data:", train_n_data
    
    #ws0 are the weights from input layer to hidden layer
    init_ws0 = initialize_weights(5, H)
    ws0 = copy.deepcopy(init_ws0)
    print "ws0 before training:", ws0

    #ws1 are the weights from hidden layer to output layer
    init_ws1 = initialize_weights(H, 1)
    init_ws1 = init_ws1[0]
    ws1 = copy.deepcopy(init_ws1)
    print "ws1 before training:", ws1
    
    epoch = 1
    
    delta2 = 0 # delta from the output layer
    delta1 = [] # deltas from hidden layer nodes
    while epoch <= 10000:
        
        i_data = 0 # index in the traning data list
        i_bs = 0 # index of batch size
        err2 = 0 # output layer error
        # one epoch
        while i_data < len(n_t):
            
            # each hidden neuron
            hidden_os = [] # hidden layer outputs
            for i in range(H):
                #print "i_data:",i_data
                hidden_o_i = sigmoid(np.inner(ws0[i], train_n_data[i_data])) # one output of one hidden layer neuron
                hidden_os.append(hidden_o_i)

            hidden_os.append(1) # append bias
            #print "hidden_os:", hidden_os
            
            sum_to_output_layer = np.inner(hidden_os, ws1) # output layer output
            net_o = sigmoid(sum_to_output_layer)
            print "net_o:", net_o
            
            err2 += error_function(net_o, o[i_data]) # output layer error
            print "err2: ", err2
            
            # only update weights after bs batch_size
            #print "o:",o
            if i_bs >= bs:
                # update ws1: weights from hidden layer to output layer
                # Derivative of err2 with respect to ws1
                # Reference: https://www.youtube.com/watch?v=zpykfC4VnpM, https://page.mi.fu-berlin.de/rojas/neural/chapter/K7.pdf
                # d_err2_ws1 = -(net_o - o[i_data]) * sigmoidPrime(net_o) * hidden_os
                delta2 = net_o * (1 - net_o) * (net_o - o[i_data])# output layers delta 
                #ws1 += ws1 + lr * err2 * hidden_os
                print "delta2:", delta2
                
                for i_hidden_node in range(H):
                    # print "hidden_os[i_hidden_node]:", hidden_os[i_hidden_node]
                    delta1.append(hidden_os[i_hidden_node] * 
                                  (1 - hidden_os[i_hidden_node]) * 
                                  delta2 * 
                                  ws1[i_hidden_node])
                
                #print "delta1: ", delta1
                
                
                delta1 = []
                delta2 = 0
                err2 = 0
                i_bs = -1
                
            hidden_os = []
            i_data += 1
            i_bs += 1
        
        
        epoch += 1
    
    
    print "Training ends."
    print "Initial input to hidden layer weights:", init_ws0
    print "Trained input to hidden layer weights:", ws0
    print "Initial hidden to output layer weights:", init_ws1
    print "Trained hidden to output layer weights:", ws1
    plot_accuracy(accuracies, lr, bs, stage="train")
    
def test(test_data, o, lr, bs):
    #normalize test data
    #normalize t
    n_test_data = normalize(test_data)
    n_t = n_test_data[:, 0]
    n_hu = n_test_data[:, 1]
    n_lt = n_test_data[:, 2]
    n_co2 = n_test_data[:, 3]
    n_hu_r = n_test_data[:, 4]
    for (n_t_i, n_hu_i, n_lt_i, n_co2_i, n_hu_r_i, o_i) in zip(n_t, n_hu, n_lt, n_co2, n_hu_r, o):
        #test every epoch
        accuracy = get_one_feedforward_accuracy(n_data, ws, o)
        accuracies.append(accuracy)
        print "epoch:", epoch, " accuracy:",accuracy
    plot_accuracy(accuracies, lr, bs, stage="test")
        
def get_one_feedforward_accuracy(n_data, ws0, ws1, o):
    
    #calculate accuracy
    #outputs
    os = []
    for each in zip(n_data):
        for ins in each:
            print "ins: ", ins
            #perceptron(ins, ws)
            
    #count correct output number
    correct_cnt = 0
    for o_i, os_i in zip(o, os):
        if (o_i == os_i):
            correct_cnt += 1
    accuracy = float(correct_cnt) / float(len(o))
    ##calculate accuracy
    return accuracy
    
def plot_accuracy(accuracies, lr, bs, stage):
    accs_y = np.array(accuracies)
    epochs = []
    for i in range(len(accuracies)):
        epochs.append(i)
    epochs_x = np.array(epochs)
    plt.plot(epochs_x, accs_y, epochs_x)
    title = stage
    title += ' lr:'
    title += str(lr)
    title += ' batch_size:'
    title += str(bs)
    plt.title(title)
    plt.xlabel('epoch')
    plt.ylabel('accuracy')
    plt.show()

In [197]:
train(n_data, o, lr = 0.0001, H = 1, bs = 1)

Training starts: len of data: 8143
n_t: [ 1.          0.99282297  0.99282297 ...,  0.50239234  0.50239234
  0.50239234]
n_hu: [ 0.47053302  0.47033188  0.46932618 ...,  0.86490111  0.87227623
  0.86959437]
n_lt: [ 0.27549041  0.27775383  0.27549041 ...,  0.28001725  0.28001725
  0.28907092]
n_b: [ 1.  1.  1. ...,  1.  1.  1.]
train_n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842  1.        ]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723  1.        ]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106  1.        ]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752  1.        ]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635  1.        ]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762  1.        ]]
ws0 before training: [[ 0.9948516   0.79763063  0.00752254  0.721847    0.50554144  0.43770722]]
ws1 before training: [ 0.43967788  0.10151297]
net_o: 0.622103096951
err2:  0.0714030346671
net_o: 0.62

net_o: 0.61264287719
err2:  0.187665647486
net_o: 0.612664235271
err2:  0.375344380076
delta2: 0.145389370822
delta1:  [0.0097590275428511616]
net_o: 0.612671350568
err2:  0.187683091903
net_o: 0.612588403363
err2:  0.375315367871
delta2: 0.145381839226
delta1:  [0.0097874750871819807]
net_o: 0.612678463833
err2:  0.187687450022
net_o: 0.612588403363
err2:  0.37531972599
delta2: 0.145381839226
delta1:  [0.0097874750871819807]
net_o: 0.612615654901
err2:  0.187648970315
net_o: 0.612649998582
err2:  0.375318980696
delta2: 0.145387957575
delta1:  [0.0097643738730572062]
net_o: 0.612608523711
err2:  0.187644601662
net_o: 0.612571742634
err2:  0.375266671599
delta2: 0.145380183198
delta1:  [0.0097937153699484952]
net_o: 0.61263995685
err2:  0.187663858365
net_o: 0.612649998582
err2:  0.375333868746
delta2: 0.145387957575
delta1:  [0.0097643738730572062]
net_o: 0.612671350568
err2:  0.187683091903
net_o: 0.612451536096
err2:  0.375231533936
delta2: 0.145368221235
delta1:  [0.0098386340165543

net_o: 0.60948920689
err2:  0.185738546658
net_o: 0.609313478773
err2:  0.371370004365
delta2: 0.145047416884
delta1:  [0.01094643150608709]
net_o: 0.609321503806
err2:  0.1856363475
net_o: 0.609536895966
err2:  0.371403961272
delta2: 0.145070798205
delta1:  [0.010871673089518072]
net_o: 0.609283366491
err2:  0.185613110341
net_o: 0.60929206858
err2:  0.371231522759
delta2: 0.145045171898
delta1:  [0.010953562681178282]
net_o: 0.609285374881
err2:  0.185614334022
net_o: 0.609301437347
err2:  0.371238454799
delta2: 0.145046154362
delta1:  [0.010950442899041554]
net_o: 0.609241959407
err2:  0.185587882551
net_o: 0.6092620641
err2:  0.371188013927
delta2: 0.145042024473
delta1:  [0.010963546690127638]
net_o: 0.609218616798
err2:  0.185573661527
net_o: 0.609278138556
err2:  0.371183586588
delta2: 0.145043710845
delta1:  [0.010958199312793673]
net_o: 0.609313478773
err2:  0.185631457707
net_o: 0.609316154013
err2:  0.371264545478
delta2: 0.145047697345
delta1:  [0.010945540048261532]
net_o:

net_o: 0.620649782459
err2:  0.0719532937741
net_o: 0.620654613032
err2:  0.143904755081
delta2: -0.0893140127491
delta1:  [-0.0038791607944119225]
net_o: 0.620615385795
err2:  0.0719663427478
net_o: 0.620631214666
err2:  0.143926680391
delta2: -0.089321663518
delta1:  [-0.0038863947869831753]
net_o: 0.620509828104
err2:  0.0720063952828
net_o: 0.620498274535
err2:  0.144017175098
delta2: -0.0893651292468
delta1:  [-0.0039274384142208209]
net_o: 0.620620299825
err2:  0.0719644784524
net_o: 0.620564903788
err2:  0.143949974571
delta2: -0.0893433449462
delta1:  [-0.0039068795787171109]
net_o: 0.620667162389
err2:  0.0719467008448
net_o: 0.620675512023
err2:  0.143890234435
delta2: -0.089307179095
delta1:  [-0.0038726969869588399]
net_o: 0.620714497544
err2:  0.0719287461865
net_o: 0.620834814655
err2:  0.143811865075
delta2: -0.0892550855844
delta1:  [-0.0038233479482696654]
net_o: 0.620898673437
err2:  0.0718589079009
net_o: 0.620862306739
err2:  0.143731603127
delta2: -0.0892460946988


net_o: 0.619420615212
err2:  0.144941083403
delta2: -0.0897172957579
delta1:  [-0.0042565569577527381]
net_o: 0.619512810587
err2:  0.0723852506538
net_o: 0.619605686858
err2:  0.144735167389
delta2: -0.0896568397058
delta1:  [-0.0042004928320300535]
net_o: 0.619634157811
err2:  0.0723390869522
net_o: 0.61978376599
err2:  0.144621279254
delta2: -0.0895986587182
delta1:  [-0.0041463675886782734]
net_o: 0.619825690944
err2:  0.0722662526329
net_o: 0.619778605568
err2:  0.144550407025
delta2: -0.0896003448272
delta1:  [-0.0041479385154015056]
net_o: 0.619742483718
err2:  0.0722978893446
net_o: 0.619840133815
err2:  0.144558651273
delta2: -0.089580240687
delta1:  [-0.004129198593741063]
net_o: 0.620031077441
err2:  0.0721881910555
net_o: 0.620001809164
err2:  0.144387503575
delta2: -0.0895274087648
delta1:  [-0.0040798566450705462]
net_o: 0.620259820861
err2:  0.0721013018264
net_o: 0.620422768895
err2:  0.144140739013
delta2: -0.089389814178
delta1:  [-0.0039507066348138135]
net_o: 0.6206

net_o: 0.607752002904
err2:  0.184681248517
net_o: 0.607970277259
err2:  0.369495177532
delta2: 0.144905106701
delta1:  [0.011382674585427729]
net_o: 0.607440536739
err2:  0.184492002837
net_o: 0.607668646556
err2:  0.36912259484
delta2: 0.144872740096
delta1:  [0.011477530933302465]
net_o: 0.60770659788
err2:  0.184653654553
net_o: 0.607911275808
err2:  0.369431714181
delta2: 0.144898787316
delta1:  [0.011401318744979436]
net_o: 0.607957317505
err2:  0.184806049954
net_o: 0.607780073713
err2:  0.369504358955
delta2: 0.144884714284
delta1:  [0.011442621941642049]
net_o: 0.607853664836
err2:  0.184743038927
net_o: 0.60777695026
err2:  0.369439449561
delta2: 0.14488437891
delta1:  [0.011443602601123185]
net_o: 0.607737992757
err2:  0.18467273392
net_o: 0.60776308184
err2:  0.369360715744
delta2: 0.144882889623
delta1:  [0.011447955347149373]
net_o: 0.607673833242
err2:  0.184633743803
net_o: 0.607544392101
err2:  0.36918883799
delta2: 0.14485936336
delta1:  [0.011516275686344944]
net_o: 

delta2: 0.144283731735
delta1:  [0.012951592377674471]
net_o: 0.602374219979
err2:  0.181427350447
net_o: 0.602721688843
err2:  0.363064067548
delta2: 0.144320656428
delta1:  [0.012872098648486359]
net_o: 0.602927780683
err2:  0.18176095436
net_o: 0.6029290975
err2:  0.363522702666
delta2: 0.14434460288
delta1:  [0.012819687934830883]
net_o: 0.602846166376
err2:  0.181711750157
net_o: 0.602784751323
err2:  0.363386478371
delta2: 0.144327944691
delta1:  [0.012856218923308581]
net_o: 0.602779507166
err2:  0.18167156713
net_o: 0.602680783719
err2:  0.363283630662
delta2: 0.144315925499
delta1:  [0.012882372919670771]
net_o: 0.60269033223
err2:  0.181617818282
net_o: 0.602651582482
err2:  0.363212283216
delta2: 0.144312546543
delta1:  [0.012889694963099555]
net_o: 0.603010840665
err2:  0.18181103698
net_o: 0.603001357299
err2:  0.363616355432
delta2: 0.144352929323
delta1:  [0.012801304647649704]
net_o: 0.603319905103
err2:  0.181997453947
net_o: 0.603329322881
err2:  0.364000589871
delta2

KeyboardInterrupt: 

In [198]:
train(n_data, o, lr = 0.0001, H = 5, bs = 1)

Training starts: len of data: 8143
n_t: [ 1.          0.99282297  0.99282297 ...,  0.50239234  0.50239234
  0.50239234]
n_hu: [ 0.47053302  0.47033188  0.46932618 ...,  0.86490111  0.87227623
  0.86959437]
n_lt: [ 0.27549041  0.27775383  0.27549041 ...,  0.28001725  0.28001725
  0.28907092]
n_b: [ 1.  1.  1. ...,  1.  1.  1.]
train_n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842  1.        ]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723  1.        ]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106  1.        ]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752  1.        ]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635  1.        ]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762  1.        ]]
ws0 before training: [[ 0.62637611  0.24666918  0.77385592  0.11180999  0.96465212  0.33314541]
 [ 0.43173649  0.03350683  0.85723793  0.21726215  0.59075131  0.07379412]
 [ 0.07183951  0.96681191  0.

delta1:  [0.0016577032133910767, 0.012053116590082747, 0.00035869947052603597, 0.011891943164271892, 0.0018740205558522675]
net_o: 0.832088962847
err2:  0.346186021046
net_o: 0.832131239375
err2:  0.692407220818
delta2: 0.116239447416
delta1:  [0.0016608247750955201, 0.012062420653838187, 0.00035946039130404996, 0.01190408788641596, 0.0018754171298298525]
net_o: 0.831787901371
err2:  0.345935556434
net_o: 0.831819289693
err2:  0.691897221787
delta2: 0.116368157236
delta1:  [0.0016838497597165593, 0.012130715307125596, 0.00035979402536139775, 0.011930711539763397, 0.0018990541936327787]
net_o: 0.831985137771
err2:  0.346099634736
net_o: 0.831749505204
err2:  0.69200325444
delta2: 0.116396910334
delta1:  [0.001684952777944912, 0.012139148470169744, 0.00036079523896063531, 0.011954931484603382, 0.0019003826787461718]
net_o: 0.831735534052
err2:  0.345891999302
net_o: 0.831721558147
err2:  0.691772374445
delta2: 0.116408421193
delta1:  [0.0016853942242513876, 0.012142521439747965, 0.000361

delta2: 0.11840982878
delta1:  [0.0019737431449192862, 0.012972015854170042, 0.00039763086082194086, 0.012791254499683713, 0.002131895819787608]
net_o: 0.826810996204
err2:  0.341808211722
net_o: 0.826863753827
err2:  0.683660045419
delta2: 0.118373886467
delta1:  [0.0019723276054503767, 0.012962700121216354, 0.00039653429304473776, 0.012761538251827756, 0.0021302212367294085]
net_o: 0.826853709325
err2:  0.341843528312
net_o: 0.826826075858
err2:  0.683664208171
delta2: 0.118388856968
delta1:  [0.0019729172833483381, 0.012966582326109838, 0.00039699181363560515, 0.012773918726341128, 0.0021309188314677175]
net_o: 0.826765728217
err2:  0.341770784677
net_o: 0.826818536636
err2:  0.683585230939
delta2: 0.118391852005
delta1:  [0.001973035241256701, 0.012967358655898755, 0.00039708321219847592, 0.012776395044666978, 0.0021310583758291806]
net_o: 0.826810996204
err2:  0.341808211722
net_o: 0.826810996204
err2:  0.683616423444
delta2: 0.118394847355
delta1:  [0.001973153206605517, 0.012968

delta1:  [0.0021517685917101827, 0.013398470287166318, 0.00041615477253816496, 0.013192083510143612, 0.0022641801238026432]
net_o: 0.824064891097
err2:  0.339541472369
net_o: 0.823888828158
err2:  0.678937872951
delta2: 0.119542995651
delta1:  [0.0021512910730270129, 0.01339558639922781, 0.0004158186060516399, 0.013182088771102928, 0.0022636139066469162]
net_o: 0.823877082107
err2:  0.33938672321
net_o: 0.824015416437
err2:  0.678887426473
delta2: 0.119493779766
delta1:  [0.0021445917277047241, 0.01337644408505728, 0.00041624905836700534, 0.013172803063942562, 0.0022526058293483404]
net_o: 0.823779287655
err2:  0.339306157385
net_o: 0.824002380325
err2:  0.678796118776
delta2: 0.119498850216
delta1:  [0.0021447907040296099, 0.013377651076003763, 0.0004163885123670719, 0.013176965989946774, 0.0022528417028743488]
net_o: 0.823998468835
err2:  0.339486738321
net_o: 0.823802809921
err2:  0.678812273138
delta2: 0.119576411514
delta1:  [0.0021565843681546036, 0.013406666323056631, 0.00041670

net_o: 0.838785574871
err2:  0.025941174411
delta2: -0.021800113311
delta1:  [-0.00027568202353719907, -0.0020180285811637333, -5.2005869539201934e-05, -0.0020602728099361942, -0.00030946619768785192]
net_o: 0.838665439561
err2:  0.013014420196
net_o: 0.838739395522
err2:  0.0260169114743
delta2: -0.0218114033502
delta1:  [-0.00027498736213186126, -0.0020209089773706021, -5.2122547335669951e-05, -0.0020637489853330428, -0.00031006729112489207]
net_o: 0.838798500497
err2:  0.012992961721
net_o: 0.83896606843
err2:  0.0259589252795
delta2: -0.0217560069401
delta1:  [-0.00027226458867831782, -0.0020080441747661608, -5.1526369295320684e-05, -0.0020502035887161076, -0.00030770481315010412]
net_o: 0.838822828108
err2:  0.0129890403696
net_o: 0.839052913203
err2:  0.0259410227437
delta2: -0.0217347970856
delta1:  [-0.00027157124061917158, -0.0020030770705738625, -5.1059293829608607e-05, -0.0020442727860697251, -0.00030752530614874812]
net_o: 0.838936994842
err2:  0.0129706458152
net_o: 0.8388

err2:  0.0130704221288
net_o: 0.838006531616
err2:  0.0261913640283
delta2: -0.0219908700255
delta1:  [-0.00027269113136834939, -0.0020404390625203433, -5.6280967012194132e-05, -0.0021536392169110839, -0.00030853115173285107]
net_o: 0.837821284057
err2:  0.35097225201
net_o: 0.837744502498
err2:  0.701880177743
delta2: 0.113873480134
delta1:  [0.0014234722767609319, 0.010613594654054991, 0.00029434418422383208, 0.011198961448042184, 0.0016067979575990177]
net_o: 0.837825855891
err2:  0.3509760824
net_o: 0.837937047056
err2:  0.702045329814
delta2: 0.113790637848
delta1:  [0.0014137076669601309, 0.010569418978306256, 0.00029224669684216553, 0.01115918640409015, 0.0015979544756110514]
net_o: 0.837772091514
err2:  0.35093103866
net_o: 0.837978287146
err2:  0.702034843524
delta2: 0.113772879707
delta1:  [0.0014123991906767389, 0.01055546271415181, 0.00029174579349167047, 0.011156302593461665, 0.0015955819262223011]
net_o: 0.837897323844
err2:  0.351035962652
net_o: 0.837856961607
err2:  0.

err2:  0.342142861386
net_o: 0.827088072259
err2:  0.684180201023
delta2: 0.118284671512
delta1:  [0.0020542190998572834, 0.013009425251460803, 0.00039620990159928526, 0.012435412166760168, 0.0021242908947188836]
net_o: 0.826859453331
err2:  0.341848277782
net_o: 0.826507188331
err2:  0.683405343963
delta2: 0.118515391514
delta1:  [0.0020814405701489402, 0.013088083391755847, 0.0004012750112265532, 0.012553430135373396, 0.0021452628512328301]
net_o: 0.826310984249
err2:  0.341394921345
net_o: 0.826371214666
err2:  0.682839613559
delta2: 0.118569254336
delta1:  [0.0020869392474554445, 0.013105856145719583, 0.00040228244079590266, 0.01258240122998967, 0.0021507611211423147]
net_o: 0.826295802436
err2:  0.341382376562
net_o: 0.826246901393
err2:  0.682724347592
delta2: 0.118618450303
delta1:  [0.0020919316821449334, 0.013119767452924352, 0.00040426585847629532, 0.012617533964201837, 0.0021510828550090318]
net_o: 0.825655539178
err2:  0.340853534688
net_o: 0.825467823696
err2:  0.681552098

delta1:  [0.0023490951843690593, 0.013824168283961673, 0.00043881150209535357, 0.0136695381664679, 0.0023975264804707483]
net_o: 0.82020062488
err2:  0.336364532526
net_o: 0.820469860394
err2:  0.672949928434
delta2: 0.120854446233
delta1:  [0.0023459921309384184, 0.013815407627777785, 0.00043799732101689452, 0.013646748968909238, 0.00239557710879544]
net_o: 0.820632566615
err2:  0.336718904694
net_o: 0.820192446483
err2:  0.673076729329
delta2: 0.120959355107
delta1:  [0.0023567323986547384, 0.013844403553539207, 0.00043906642424064294, 0.013692558265558758, 0.0024084996307455571]
net_o: 0.820408691643
err2:  0.336535210662
net_o: 0.820416851413
err2:  0.673077115703
delta2: 0.120874509878
delta1:  [0.0023467539456843195, 0.013819619149752093, 0.00043845899462111748, 0.013663114458000242, 0.0023965021927635985]
net_o: 0.820212890203
err2:  0.336374592628
net_o: 0.820216978039
err2:  0.672752538159
delta2: 0.120950087138
delta1:  [0.0023563814420406218, 0.013842475585809574, 0.00043885

delta1:  [0.0024569942365539566, 0.014044284891686028, 0.0004541526161552872, 0.014020907822124513, 0.0024559444908447687]
net_o: 0.818119370023
err2:  0.334659651803
net_o: 0.818235927842
err2:  0.669414668609
delta2: 0.12169287006
delta1:  [0.0024526325018733898, 0.014036309367610276, 0.00045361714927040145, 0.014009860052266525, 0.0024539487918784765]
net_o: 0.817817378225
err2:  0.334412632064
net_o: 0.817579922229
err2:  0.66863109668
delta2: 0.121936316616
delta1:  [0.0024795837040083924, 0.014098089885694715, 0.00045579021001358391, 0.014098715007222019, 0.0024833856389772273]
net_o: 0.817557911708
err2:  0.334200469498
net_o: 0.817717584177
err2:  0.668531493234
delta2: 0.121885333383
delta1:  [0.0024746645805868326, 0.014086624688876476, 0.00045490455151628588, 0.014071045936847959, 0.0024804965392074365]
net_o: 0.817605674802
err2:  0.334239519735
net_o: 0.817483690154
err2:  0.668379311568
delta2: 0.121971923556
delta1:  [0.0024845119958639859, 0.014106961295098494, 0.000456

delta1:  [-0.00041012547750562348, -0.0025463984594421944, -7.518626990253387e-05, -0.0025657948812773581, -0.00041592559212583387]
net_o: 0.829459135004
err2:  0.0145420933167
net_o: 0.829495748925
err2:  0.029077943134
delta2: -0.0241148512609
delta1:  [-0.00041015755339015507, -0.0025435040564689431, -7.4950190620319977e-05, -0.0025587028001716858, -0.00041540035256132878]
net_o: 0.82943526869
err2:  0.0145461637833
net_o: 0.829497808879
err2:  0.0290816623718
delta2: -0.0241143284602
delta1:  [-0.00040966343939354802, -0.0025432904190610759, -7.4934662796457256e-05, -0.0025592767893601559, -0.00041541818861756528]
net_o: 0.829703092614
err2:  0.0145005183325
net_o: 0.829833987333
err2:  0.028978754266
delta2: -0.0240290645085
delta1:  [-0.00040490975000679789, -0.0025257245624518178, -7.4211649762220318e-05, -0.0025404544531060272, -0.0004112782880241294]
net_o: 0.829930026925
err2:  0.0144618978709
net_o: 0.830169330438
err2:  0.0288831260329
delta2: -0.0239441226547
delta1:  [-0.

delta2: -0.0228962024826
delta1:  [-0.00033913076239592448, -0.0022421134947068449, -6.8203204229967191e-05, -0.0023633164688471793, -0.00033780029304996615]
net_o: 0.834679017187
err2:  0.0136655136792
net_o: 0.834660987538
err2:  0.0273340082001
delta2: -0.0228171182699
delta1:  [-0.00033567916190061761, -0.0022285097064847423, -6.7351108366528153e-05, -0.0023377263642189706, -0.00033505088848637495]
net_o: 0.83485646935
err2:  0.0136361928577
net_o: 0.834743689164
err2:  0.0272910169933
delta2: -0.0227965565476
delta1:  [-0.00033464349667550056, -0.002224609735691527, -6.7293120964020126e-05, -0.0023320614819434763, -0.00033373419877020882]
net_o: 0.834875039283
err2:  0.0136331263259
net_o: 0.83502363557
err2:  0.0272417267362
delta2: -0.0227270059792
delta1:  [-0.00033059642615400282, -0.0022094139629418434, -6.6335739596534225e-05, -0.0023149544431494756, -0.00033163606905905254]
net_o: 0.83485919917
err2:  0.0136357420494
net_o: 0.834884800551
err2:  0.027267256594
delta2: -0.02

delta2: 0.120090628391
delta1:  [0.0022979923877394222, 0.013612752966108331, 0.00043190164415574513, 0.013213907982823231, 0.0022931286354540168]
net_o: 0.822425618278
err2:  0.3381919488
net_o: 0.822393912254
err2:  0.676357822257
delta2: 0.120120635587
delta1:  [0.0022992678260582333, 0.01361954244530225, 0.000432624600885316, 0.013238174366940116, 0.002294547084232477]
net_o: 0.821844965106
err2:  0.337714573335
net_o: 0.822269840933
err2:  0.675778418989
delta2: 0.120168282126
delta1:  [0.002304729557099081, 0.013632906243216432, 0.00043372147697005631, 0.013263541081633679, 0.0022973702827651619]
net_o: 0.821817032605
err2:  0.33769161754
net_o: 0.821737143935
err2:  0.675317584401
delta2: 0.120372338269
delta1:  [0.0023275230307642334, 0.013694844744811105, 0.00043552787225692181, 0.013344228549634761, 0.002325142368452467]
net_o: 0.821734478899
err2:  0.337623776906
net_o: 0.821693153685
err2:  0.675213596312
delta2: 0.120389152093
delta1:  [0.0023281649827142327, 0.01369850814

err2:  0.665719138943
delta2: 0.122554673311
delta1:  [0.0025468192329971924, 0.014248472936208576, 0.00045916480636710739, 0.014282359178325604, 0.0025715442768677638]
net_o: 0.815677503129
err2:  0.332664894556
net_o: 0.815531878303
err2:  0.66521101682
delta2: 0.122688317103
delta1:  [0.0025600972930074259, 0.01427904387016294, 0.00045942926585014151, 0.014317224123815633, 0.0025932908352853906]
net_o: 0.815024881123
err2:  0.332132778425
net_o: 0.815567511024
err2:  0.664707960944
delta2: 0.122675337367
delta1:  [0.0025571224312413679, 0.014275556419436741, 0.00045922001338793826, 0.014319502808667964, 0.0025922225408212892]
net_o: 0.815576093991
err2:  0.332582182545
net_o: 0.815489581319
err2:  0.665093811165
delta2: 0.122703719626
delta1:  [0.0025593708349332866, 0.014281026485906003, 0.00045970150956002625, 0.014336082257277784, 0.0025937359966720823]
net_o: 0.815476055941
err2:  0.332500598906
net_o: 0.815576093991
err2:  0.665082781452
delta2: 0.122672210348
delta1:  [0.00255

delta2: 0.122754993138
delta1:  [0.0025644318993035872, 0.014294101077006223, 0.0004587353812889152, 0.014333399147709222, 0.0026092890333411318]
net_o: 0.815368014485
err2:  0.332412499522
net_o: 0.815423804941
err2:  0.664870490355
delta2: 0.122727661929
delta1:  [0.002561826068885525, 0.014288675290303256, 0.00045825790428284777, 0.014319734745002942, 0.0026077530999832656]
net_o: 0.815389494326
err2:  0.332430013729
net_o: 0.815661223249
err2:  0.665081629284
delta2: 0.122641183792
delta1:  [0.0025530285831315593, 0.014269680483905589, 0.00045769688994763181, 0.014292713190612844, 0.0025964852581604196]
net_o: 0.815407175822
err2:  0.332444431191
net_o: 0.81539428924
err2:  0.664878354654
delta2: 0.122738401443
delta1:  [0.0025626136370387746, 0.01429069306630697, 0.00045844752285019924, 0.014326316145828346, 0.0026083112182955764]
net_o: 0.815346527135
err2:  0.332394979656
net_o: 0.815399076229
err2:  0.664832806414
delta2: 0.122736659832
delta1:  [0.0025613038700745966, 0.014289

KeyboardInterrupt: 

In [111]:
test_data = np.genfromtxt('../data/assign2_test_data.txt', delimiter=',')
# print "test_data:", test_data
test(test_data, o, lr, bs)

NameError: global name 'ws' is not defined