In [1]:
import numpy as np
import random

train_data = np.genfromtxt('../data/assign2_train_data.txt', delimiter=',')
#print "train_data:", train_data

t = train_data[:,2]
hu = train_data[:,3]
lt = train_data[:,4]
co2 = train_data[:,5]
hu_r = train_data[:,6]

o = train_data[:,7]

#data
data = np.column_stack((t, hu, lt, co2, hu_r))
print "data:", data

print "np.shape(train_data): ", np.shape(train_data)
#print "np.shape(t): ", np.shape(t)

print "t: ", t
print "hu: ", hu
print "lt: ", lt
print "co2: ", co2
print "hu_r: ", hu_r
print "o: ", o

data: [[  2.31800000e+01   2.72720000e+01   4.26000000e+02   7.21250000e+02
    4.79298818e-03]
 [  2.31500000e+01   2.72675000e+01   4.29500000e+02   7.14000000e+02
    4.78344095e-03]
 [  2.31500000e+01   2.72450000e+01   4.26000000e+02   7.13500000e+02
    4.77946352e-03]
 ..., 
 [  2.11000000e+01   3.60950000e+01   4.33000000e+02   7.98500000e+02
    5.59563902e-03]
 [  2.11000000e+01   3.62600000e+01   4.33000000e+02   8.20333333e+02
    5.62144937e-03]
 [  2.11000000e+01   3.62000000e+01   4.47000000e+02   8.21000000e+02
    5.61206354e-03]]
np.shape(train_data):  (8143, 8)
t:  [ 23.18  23.15  23.15 ...,  21.1   21.1   21.1 ]
hu:  [ 27.272   27.2675  27.245  ...,  36.095   36.26    36.2   ]
lt:  [ 426.   429.5  426.  ...,  433.   433.   447. ]
co2:  [ 721.25        714.          713.5        ...,  798.5         820.33333333
  821.        ]
hu_r:  [ 0.00479299  0.00478344  0.00477946 ...,  0.00559564  0.00562145
  0.00561206]
o:  [ 1.  1.  1. ...,  1.  1.  1.]


In [2]:
#normalize inputs

#normalize t
t_min = np.min(t)
t_max = np.max(t)
d_t = t_max - t_min
#normalized t: n_t
n_t = []
for each in t:
    n_t.append((each - t_min) / d_t)

#normalize hu
hu_min = np.min(hu)
hu_max = np.max(hu)
d_hu = hu_max - hu_min
#normalized h: n_hu
n_hu = []
for each in hu:
    n_hu.append((each - hu_min) / d_hu)

#normalize lt
lt_min = np.min(lt)
lt_max = np.max(lt)
d_lt = lt_max - lt_min
#normalized lt: n_lt
n_lt = []
for each in lt:
    n_lt.append((each - lt_min) / d_lt)

#normalize co2
co2_min = np.min(co2)
co2_max = np.max(co2)
d_co2 = co2_max - co2_min
#normalized co2: n_co2
n_co2 = []
for each in co2:
    n_co2.append((each - co2_min) / d_co2)

#normalize hu_r
hu_r_min = np.min(hu_r)
hu_r_max = np.max(hu_r)
d_hu_r = hu_r_max - hu_r_min
#normalized hu_r: n_hu_r
n_hu_r = []
for each in hu_r:
    n_hu_r.append((each - hu_r_min) / d_hu_r)
    
#normalized data: n_data
n_data = np.column_stack((n_t, n_hu, n_lt, n_co2, n_hu_r))
print "n_data:", n_data

n_data: [[ 1.          0.47053302  0.27549041  0.190933    0.55731842]
 [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723]
 [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106]
 ..., 
 [ 0.50239234  0.86490111  0.28001725  0.23874362  0.76843752]
 [ 0.50239234  0.87227623  0.28001725  0.25225643  0.77522635]
 [ 0.50239234  0.86959437  0.28907092  0.25266904  0.77275762]]


In [3]:
def initialize_weights():
    w_t = random.random()
    w_hu = random.random()
    w_lt = random.random()
    w_co2 = random.random()
    w_hu_r = random.random()
    b = random.random()

    #weights
    ws = [w_t, w_hu, w_lt, w_co2, w_hu_r, b]
    return ws

ws = initialize_weights()
print "ws: ", ws

ws:  [0.18566901734499108, 0.5436871826460499, 0.6426783189020007, 0.6423403232585331, 0.9821881284505821, 0.7383745830734532]


In [44]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def activation(x): # use sigmoid as activation function
    a = sigmoid(x)
    if a >= 0.5:
        return 1
    else:
        return 0

def perceptron(ins, ws):
    sum = 0
    for x, w in zip(ins, ws):
        sum += x * w
    return activation(sum)

# lr - learning rate
# bs - batch size
def train(n_data, lr, bs):
    
    #outputs
    os = []
    
    for each in zip(n_data):
        for ins in each:
            os.append(perceptron(ins, ws))
            
    accuracy = []
    epoch = 0
    while epoch <= 2500:
        # train
        i = 0
        print "n_t:",n_t
        for (n_t_i, n_hu_i, n_lt_i, n_co2_i, n_hu_r_i, o_i) in zip(n_t, n_hu, n_lt, n_co2, n_hu_r, o):
            sum_error_w_t = 0
            sum_error_w_hu = 0
            sum_error_w_lt = 0
            sum_error_w_co2 = 0
            sum_error_w_hu_r = 0
            sum_error_b = 0
            
            error = o_i - (n_t_i * w_t + n_hu_i * w_hu + n_co2_i * w_co2 + n_hu_r_i * w_hu_r + b)
            sum_error_w_t += error * n_t_i
            sum_error_w_hu += error * n_hu_i
            sum_error_w_lt += error * n_lt_i
            sum_error_w_co2 += error * n_co2_i
            sum_error_w_hu_r += error * n_hu_r_i
            sum_error_b += error
            
            if i >= bs: # only update weights after one batch size
                w_t += lr * sum_error_w_t
                w_hu += lr * sum_error_w_hu
                w_lt += lr * sum_error_w_lt
                w_co2 += lr * sum_error_w_co2
                w_hu_r += lr * sum_error_w_hu_r
                w_b += lr * sum_error_b
                sum_error_w_t = 0
                sum_error_w_hu = 0
                sum_error_w_lt = 0
                sum_error_w_co2 = 0
                sum_error_w_hu_r = 0
                sum_error_b = 0
                i = 1
                continue
            i += 1
        
        # count 
        
        epoch += 1

In [45]:
train(n_data, lr = 0.0001, bs = 1)

ins_i: [ 1.          0.47053302  0.27549041  0.190933    0.55731842]
ins_i: [ 0.99282297  0.47033188  0.27775383  0.18644592  0.55480723]
ins_i: [ 0.99282297  0.46932618  0.27549041  0.18613647  0.55376106]
ins_i: [ 0.99282297  0.46731478  0.27549041  0.1828872   0.55166876]
ins_i: [ 0.98086124  0.46731478  0.27549041  0.1805663   0.54785068]
ins_i: [ 0.98086124  0.46731478  0.27096357  0.17840012  0.54785068]
ins_i: [ 0.98086124  0.46731478  0.27096357  0.17881273  0.54785068]
ins_i: [ 0.98086124  0.46731478  0.27096357  0.17716231  0.54785068]
ins_i: [ 0.98086124  0.46731478  0.27096357  0.17117953  0.54785068]
ins_i: [ 0.97488038  0.46619734  0.27096357  0.17035432  0.54478846]
ins_i: [ 0.97488038  0.4650799   0.27096357  0.17174687  0.54363145]
ins_i: [ 0.98086124  0.46284501  0.27096357  0.17221105  0.54321556]
ins_i: [ 0.98086124  0.46582486  0.27096357  0.16756924  0.54630561]
ins_i: [ 0.96889952  0.4650799   0.27096357  0.17004487  0.54173237]
ins_i: [ 0.9569378   0.46396245  0

ins_i: [ 0.62200957  0.43110962  0.          0.05833204  0.40375015]
ins_i: [ 0.62200957  0.43110962  0.          0.05616587  0.40375015]
ins_i: [ 0.62200957  0.43110962  0.          0.05647532  0.40375015]
ins_i: [ 0.62200957  0.43110962  0.          0.05647532  0.40375015]
ins_i: [ 0.61602871  0.42775729  0.          0.05430914  0.39888363]
ins_i: [ 0.62200957  0.42663985  0.          0.05399969  0.39952665]
ins_i: [ 0.62200957  0.42663985  0.          0.05616587  0.39952665]
ins_i: [ 0.61004785  0.42462845  0.          0.05585641  0.39423985]
ins_i: [ 0.61004785  0.42462845  0.          0.05554696  0.39423985]
ins_i: [ 0.59808612  0.42261705  0.          0.05523751  0.38897404]
ins_i: [ 0.61403509  0.42261705  0.          0.05523751  0.39347106]
ins_i: [ 0.59808612  0.42261705  0.          0.05554696  0.38897404]
ins_i: [ 0.59808612  0.42261705  0.          0.05214297  0.38897404]
ins_i: [ 0.59808612  0.42038217  0.          0.05492805  0.38687553]
ins_i: [ 0.59808612  0.42038217  0

ins_i: [ 0.45215311  0.29254665  0.          0.02212595  0.23107001]
ins_i: [ 0.45215311  0.29254665  0.          0.02181649  0.23107001]
ins_i: [ 0.45215311  0.29254665  0.          0.02336376  0.23107001]
ins_i: [ 0.45215311  0.28852386  0.          0.02367322  0.2274385 ]
ins_i: [ 0.45215311  0.28852386  0.          0.02491103  0.2274385 ]
ins_i: [ 0.45215311  0.28852386  0.          0.0224354   0.2274385 ]
ins_i: [ 0.45215311  0.28852386  0.          0.02212595  0.2274385 ]
ins_i: [ 0.45215311  0.28852386  0.          0.02212595  0.2274385 ]
ins_i: [ 0.45215311  0.28628897  0.          0.02212595  0.22542106]
ins_i: [ 0.45215311  0.28628897  0.          0.02522049  0.22542106]
ins_i: [ 0.44019139  0.28293664  0.          0.02367322  0.21953511]
ins_i: [ 0.45215311  0.28405408  0.          0.02387952  0.22340367]
ins_i: [ 0.45215311  0.28405408  0.          0.02429212  0.22340367]
ins_i: [ 0.45215311  0.28405408  0.          0.02460158  0.22340367]
ins_i: [ 0.44417863  0.28256416  0

ins_i: [ 0.83732057  0.47133758  0.31019616  0.40801485  0.50684699]
ins_i: [ 0.83732057  0.46832048  0.30830998  0.40847903  0.50383152]
ins_i: [ 0.83732057  0.46832048  0.30814831  0.40925267  0.50383152]
ins_i: [ 0.83732057  0.46731478  0.30653158  0.40615813  0.50282639]
ins_i: [ 0.83732057  0.4650799   0.31138176  0.40569395  0.5005928 ]
ins_i: [ 0.83732057  0.46832048  0.30653158  0.41281139  0.50383152]
ins_i: [ 0.83074163  0.46720304  0.30976504  0.41606065  0.50068598]
ins_i: [ 0.83732057  0.46582486  0.30329812  0.40430141  0.50133732]
ins_i: [ 0.83732057  0.46396245  0.30653158  0.40275414  0.49947603]
ins_i: [ 0.83732057  0.4650799   0.30329812  0.40399195  0.5005928 ]
ins_i: [ 0.83732057  0.46396245  0.30653158  0.40755067  0.49947603]
ins_i: [ 0.83732057  0.46135509  0.30976504  0.40553922  0.49687029]
ins_i: [ 0.83732057  0.46284501  0.30944169  0.40352777  0.49835927]
ins_i: [ 0.83732057  0.46284501  0.30944169  0.40724122  0.49835927]
ins_i: [ 0.83732057  0.46284501  0

ins_i: [ 0.36483254  0.10414571  0.          0.01191397  0.04408846]
ins_i: [ 0.35885167  0.10302827  0.          0.0103667   0.04194858]
ins_i: [ 0.35885167  0.10526316  0.          0.01469906  0.04391373]
ins_i: [ 0.36682616  0.10079338  0.          0.01232658  0.04152079]
ins_i: [ 0.3708134   0.10079338  0.          0.01067616  0.0422905 ]
ins_i: [ 0.35885167  0.09833501  0.          0.00758162  0.03782193]
ins_i: [ 0.3708134   0.10079338  0.          0.00789107  0.0422905 ]
ins_i: [ 0.3708134   0.10079338  0.          0.01315179  0.0422905 ]
ins_i: [ 0.35885167  0.10079338  0.          0.01253288  0.03998348]
ins_i: [ 0.35885167  0.10079338  0.          0.01253288  0.03998348]
ins_i: [ 0.38277512  0.09915447  0.          0.01284233  0.04315377]
ins_i: [ 0.35885167  0.10079338  0.          0.00820053  0.03998348]
ins_i: [ 0.36682616  0.09915447  0.          0.00840683  0.04007675]
ins_i: [ 0.36682616  0.09751555  0.          0.01067616  0.03863274]
ins_i: [ 0.38277512  0.09833501  0

ins_i: [ 0.64593301  0.15543636  0.32350722  0.23332818  0.14889391]
ins_i: [ 0.64593301  0.15443066  0.3194654   0.22744855  0.14794073]
ins_i: [ 0.64593301  0.15294074  0.32162104  0.22873794  0.14652863]
ins_i: [ 0.64593301  0.14996089  0.32054322  0.22688122  0.14370451]
ins_i: [ 0.64593301  0.1517488   0.31817202  0.22327093  0.14539897]
ins_i: [ 0.64593301  0.15219578  0.32916577  0.22213626  0.14582259]
ins_i: [ 0.64593301  0.14549112  0.32916577  0.22048584  0.13946851]
ins_i: [ 0.64593301  0.14549112  0.32027377  0.2167724   0.13946851]
ins_i: [ 0.64593301  0.14549112  0.32269886  0.21491567  0.13946851]
ins_i: [ 0.64593301  0.14996089  0.31623195  0.20996441  0.14370451]
ins_i: [ 0.64593301  0.15107833  0.31122009  0.2133684   0.14476354]
ins_i: [ 0.64593301  0.14660856  0.31623195  0.21429677  0.14052749]
ins_i: [ 0.64593301  0.14549112  0.24428756  0.21352313  0.13946851]
ins_i: [ 0.64593301  0.14884345  0.02845441  0.21166641  0.14264549]
ins_i: [ 0.64593301  0.14884345  0

ins_i: [ 0.21291866  0.09140686  0.          0.01542112  0.00439484]
ins_i: [ 0.21291866  0.09140686  0.          0.01779359  0.00439484]
ins_i: [ 0.23923445  0.08939546  0.          0.01377069  0.00754298]
ins_i: [ 0.23923445  0.08738407  0.          0.01748414  0.00582894]
ins_i: [ 0.23923445  0.08738407  0.          0.01748414  0.00582894]
ins_i: [ 0.23923445  0.08738407  0.          0.01686523  0.00582894]
ins_i: [ 0.23923445  0.08738407  0.          0.01562742  0.00582894]
ins_i: [ 0.2326555   0.08939546  0.          0.01294548  0.00632762]
ins_i: [ 0.23923445  0.09140686  0.          0.01346124  0.00925706]
ins_i: [ 0.23923445  0.08738407  0.          0.01315179  0.00582894]
ins_i: [ 0.23923445  0.08939546  0.          0.01593687  0.00754298]
ins_i: [ 0.23923445  0.08939546  0.          0.01872196  0.00754298]
ins_i: [ 0.23923445  0.08939546  0.          0.01500851  0.00754298]
ins_i: [ 0.23923445  0.09140686  0.          0.01469906  0.00925706]
ins_i: [ 0.23923445  0.088725    0

ins_i: [ 0.26315789  0.11375573  0.08439319  0.02924339  0.03286981]
ins_i: [ 0.27113238  0.11107386  0.08902781  0.02738666  0.03209198]
ins_i: [ 0.27511962  0.11073863  0.0890817   0.02614885  0.03256582]
ins_i: [ 0.27113238  0.10973293  0.09269239  0.02697406  0.03093946]
ins_i: [ 0.28708134  0.10973293  0.09157146  0.03032647  0.0339879 ]
ins_i: [ 0.30322967  0.10973293  0.09813537  0.02899582  0.03708579]
ins_i: [ 0.30322967  0.10861549  0.09829705  0.02614885  0.0361173 ]
ins_i: [ 0.30861244  0.10861549  0.1015305   0.0257775   0.03715111]
ins_i: [ 0.30861244  0.10749804  0.09894374  0.02831502  0.03618127]
ins_i: [ 0.32655502  0.10526316  0.10702738  0.02661303  0.03768323]
ins_i: [ 0.33253589  0.10414571  0.1086441   0.02614885  0.03785769]
ins_i: [ 0.33253589  0.10228331  0.11209312  0.02676775  0.03623127]
ins_i: [ 0.33253589  0.10079338  0.10751239  0.0264583   0.03493015]
ins_i: [ 0.34569378  0.10302827  0.11026083  0.02522049  0.03941141]
ins_i: [ 0.35885167  0.10191083  0

ins_i: [ 0.21291866  0.42261705  0.          0.01748414  0.28519397]
ins_i: [ 0.21291866  0.42663985  0.          0.01624633  0.28861039]
ins_i: [ 0.21291866  0.42663985  0.          0.01717469  0.28861039]
ins_i: [ 0.21291866  0.42663985  0.          0.01934086  0.28861039]
ins_i: [ 0.21291866  0.42663985  0.          0.01624633  0.28861039]
ins_i: [ 0.21291866  0.42663985  0.          0.01562742  0.28861039]
ins_i: [ 0.21291866  0.42663985  0.          0.01562742  0.28861039]
ins_i: [ 0.21291866  0.43110962  0.          0.01686523  0.29240657]
ins_i: [ 0.21291866  0.43110962  0.          0.01872196  0.29240657]
ins_i: [ 0.18899522  0.43110962  0.          0.01377069  0.28621256]
ins_i: [ 0.21291866  0.44049614  0.          0.01624633  0.30037913]
ins_i: [ 0.21291866  0.44049614  0.          0.01562742  0.30037913]
ins_i: [ 0.1969697   0.44049614  0.          0.01707154  0.29621271]
ins_i: [ 0.18899522  0.43602637  0.          0.01562742  0.29036243]
ins_i: [ 0.1969697   0.44049614  0

ins_i: [ 0.04784689  0.64610571  0.          0.01408015  0.42538558]
ins_i: [ 0.04784689  0.64312586  0.          0.01253288  0.42295711]
ins_i: [ 0.04784689  0.64163594  0.          0.01067616  0.4217429 ]
ins_i: [ 0.04784689  0.64163594  0.          0.01191397  0.4217429 ]
ins_i: [ 0.04784689  0.64163594  0.          0.01129506  0.4217429 ]
ins_i: [ 0.06937799  0.64610571  0.          0.01315179  0.43177704]
ins_i: [ 0.05861244  0.64387082  0.          0.01129506  0.42675078]
ins_i: [ 0.04784689  0.64163594  0.          0.01098561  0.4217429 ]
ins_i: [ 0.04784689  0.64163594  0.          0.01005725  0.4217429 ]
ins_i: [ 0.05861244  0.64387082  0.          0.00912889  0.42675078]
ins_i: [ 0.04784689  0.64163594  0.          0.0103667   0.4217429 ]
ins_i: [ 0.04784689  0.64163594  0.          0.0143896   0.4217429 ]
ins_i: [ 0.04784689  0.64163594  0.          0.01408015  0.4217429 ]
ins_i: [ 0.06220096  0.64461579  0.          0.01480221  0.42842416]
ins_i: [ 0.06937799  0.64610571  0

ins_i: [ 0.10645933  0.46731478  0.          0.00881943  0.29501045]
ins_i: [ 0.09330144  0.46731478  0.          0.0057249   0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.0063438   0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00510599  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.0059312   0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00696271  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00820053  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00943834  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00912889  0.29157878]
ins_i: [ 0.1108453   0.46999665  0.          0.00943834  0.29837499]
ins_i: [ 0.09330144  0.46731478  0.          0.00758162  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00850998  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.00820053  0.29157878]
ins_i: [ 0.09330144  0.46731478  0.          0.0057249   0.29157878]
ins_i: [ 0.09330144  0.46731478  0

ins_i: [ 0.09330144  0.44697732  0.          0.03357574  0.27483585]
ins_i: [ 0.09330144  0.44697732  0.          0.03419465  0.27483585]
ins_i: [ 0.09330144  0.44496592  0.          0.03233792  0.27318014]
ins_i: [ 0.09330144  0.44496592  0.          0.03233792  0.27318014]
ins_i: [ 0.09330144  0.44496592  0.          0.02800557  0.27318014]
ins_i: [ 0.09330144  0.44496592  0.          0.02986229  0.27318014]
ins_i: [ 0.09330144  0.44496592  0.          0.03295683  0.27318014]
ins_i: [ 0.10645933  0.44697732  0.          0.03202847  0.27820943]
ins_i: [ 0.10645933  0.44496592  0.          0.02893393  0.27654797]
ins_i: [ 0.09330144  0.44496592  0.          0.02759297  0.27318014]
ins_i: [ 0.11961722  0.44496592  0.          0.02986229  0.27992605]
ins_i: [ 0.11961722  0.44496592  0.          0.02924339  0.27992605]
ins_i: [ 0.10645933  0.44697732  0.          0.02955284  0.27820943]
ins_i: [ 0.11961722  0.44496592  0.          0.02986229  0.27992605]
ins_i: [ 0.11961722  0.44496592  0

ins_i: [ 0.64593301  0.81595709  0.30572322  0.61086183  0.77731729]
ins_i: [ 0.64593301  0.81997989  0.30545376  0.60998504  0.78115931]
ins_i: [ 0.65669856  0.82668455  0.30976504  0.62246635  0.79170743]
ins_i: [ 0.64593301  0.8275785   0.30653158  0.62875857  0.78841696]
ins_i: [ 0.64593301  0.83137781  0.30006467  0.63639177  0.79204603]
ins_i: [ 0.65311005  0.83383618  0.30006467  0.63577286  0.79716886]
ins_i: [ 0.65669856  0.83718851  0.30685493  0.64381866  0.80176915]
ins_i: [ 0.66208134  0.84132305  0.30006467  0.65078137  0.80782559]
ins_i: [ 0.66028708  0.84232875  0.30006467  0.65372118  0.80809112]
ins_i: [ 0.66746411  0.84478713  0.30006467  0.654959    0.81325176]
ins_i: [ 0.66746411  0.84601631  0.30006467  0.65867244  0.81443269]
ins_i: [ 0.66746411  0.84601631  0.30006467  0.66269534  0.81443269]
ins_i: [ 0.66746411  0.85372667  0.30685493  0.67074114  0.82184068]
ins_i: [ 0.67344498  0.85372667  0.30442983  0.6716695   0.8241936 ]
ins_i: [ 0.66746411  0.85454613  0

ins_i: [ 0.29784689  0.72209185  0.          0.03481355  0.56775841]
ins_i: [ 0.29784689  0.72432674  0.          0.03264738  0.56970524]
ins_i: [ 0.30861244  0.72656163  0.          0.02986229  0.57523159]
ins_i: [ 0.30861244  0.72656163  0.          0.03357574  0.57523159]
ins_i: [ 0.30861244  0.72656163  0.          0.03460725  0.57523159]
ins_i: [ 0.30861244  0.72656163  0.          0.03605137  0.57523159]
ins_i: [ 0.30861244  0.72656163  0.          0.03543246  0.57523159]
ins_i: [ 0.30861244  0.72432674  0.          0.03419465  0.5732792 ]
ins_i: [ 0.30861244  0.72209185  0.          0.03295683  0.57132686]
ins_i: [ 0.30861244  0.72432674  0.          0.03110011  0.5732792 ]
ins_i: [ 0.30861244  0.72432674  0.          0.03110011  0.5732792 ]
ins_i: [ 0.30861244  0.72209185  0.          0.03130641  0.57132686]
ins_i: [ 0.30861244  0.72656163  0.          0.03233792  0.57523159]
ins_i: [ 0.30861244  0.72656163  0.          0.03233792  0.57523159]
ins_i: [ 0.30861244  0.72209185  0

UnboundLocalError: local variable 'w_t' referenced before assignment